using System.IO;using System.Text;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using BefundExplorer.Core.Data;using BefundExplorer.Core.Models;using BefundExplorer.Core.Search;using Microsoft.Win32;
namespace BefundExplorer.App;
public partial class MainWindow:Window
{const string DbName="Radiologie_Befunddatenbank_CT_MR.sqlite";SqliteReportRepository? repo;ReportRecord? current;int page=1,totalPages=1;CancellationTokenSource? cts;bool dark;
public MainWindow(){InitializeComponent();CommandBindings.Add(new CommandBinding(ApplicationCommands.Find,(_,_)=>{SearchBox.Focus();SearchBox.SelectAll();}));}
async void Window_Loaded(object sender,RoutedEventArgs e){var path=Path.Combine(AppContext.BaseDirectory,DbName);if(!File.Exists(path)){MessageBox.Show(this,$"Die Datenbank wurde nicht gefunden.\n\nErwartet neben der Anwendung:\n{DbName}","BefundExplorer",MessageBoxButton.OK,MessageBoxImage.Error);Close();return;}try{repo=new(path);var f=await repo.GetFilterOptionsAsync();StudyBox.Items.Add("Alle Studien");foreach(var s in f.StudyDescriptions)StudyBox.Items.Add(s);StudyBox.SelectedIndex=0;StatusBox.Items.Add("Alle Status");foreach(var s in f.StructureStatuses)StatusBox.Items.Add(s);StatusBox.SelectedIndex=0;DbInfo.Text=$"{f.TotalCount:N0} Befunde\nCT {f.CtCount:N0} · MR {f.MrCount:N0}\n{DbName}";await SearchAsync(1);}catch(Exception ex){MessageBox.Show(this,"Datenbank konnte nicht geöffnet werden:\n"+ex.Message,"BefundExplorer",MessageBoxButton.OK,MessageBoxImage.Error);}}
SearchRequest Request(int p){bool? imp=((ComboBoxItem)ImpressionBox.SelectedItem).Tag?.ToString() switch{"yes"=>true,"no"=>false,_=>null};return new(SearchBox.Text,Enum.Parse<SearchMode>(((ComboBoxItem)ModeBox.SelectedItem).Tag!.ToString()!),Enum.Parse<SearchField>(((ComboBoxItem)FieldBox.SelectedItem).Tag!.ToString()!),CtCheck.IsChecked==true,MrCheck.IsChecked==true,StudyBox.SelectedIndex>0?StudyBox.Text:null,StatusBox.SelectedIndex>0?StatusBox.SelectedItem?.ToString():null,imp,p,int.Parse(((ComboBoxItem)PageSizeBox.SelectedItem).Content.ToString()!),Enum.Parse<SortMode>(((ComboBoxItem)SortBox.SelectedItem).Tag!.ToString()!));}
async Task SearchAsync(int p){if(repo is null)return;cts?.Cancel();cts?.Dispose();cts=new();try{StatusText.Text="Suche …";SearchBox.IsEnabled=false;var req=Request(p);var result=await repo.SearchAsync(req,cts.Token);page=result.Page;totalPages=result.TotalPages;ResultsList.ItemsSource=result.Items;ResultCount.Text=$"{result.TotalCount:N0} Treffer";PageText.Text=$"Seite {page:N0} / {totalPages:N0}";PrevButton.IsEnabled=page>1;NextButton.IsEnabled=page<totalPages;StatusText.Text=result.TotalCount==0?"Keine Treffer.":$"{result.TotalCount:N0} Treffer · {result.Items.Count:N0} angezeigt";if(result.Items.Count>0)ResultsList.SelectedIndex=0;else ClearDetail();}catch(OperationCanceledException){}catch(Exception ex){StatusText.Text="Suchfehler";MessageBox.Show(this,ex.Message,"Suchfehler",MessageBoxButton.OK,MessageBoxImage.Warning);}finally{SearchBox.IsEnabled=true;}}
async void ResultsList_SelectionChanged(object sender,SelectionChangedEventArgs e){if(repo is null||ResultsList.SelectedItem is not ReportSummary s)return;current=await repo.GetByIdAsync(s.Id);if(current is null)return;DetailHeader.Text=string.IsNullOrWhiteSpace(current.Title)?current.StudyDescription:current.Title;DetailMeta.Text=$"{current.Modality} · {current.StudyDescription} · #{current.Id} · {current.StructureStatus}";ClinicalText.Text=current.ClinicalInformation;QuestionText.Text=current.Question;TechniqueText.Text=current.Technique;FindingsText.Text=current.Findings;ImpressionText.Text=current.Impression;OriginalText.Text=current.OriginalText;}
void ClearDetail(){current=null;DetailHeader.Text="BEFUND";DetailMeta.Text="";ClinicalText.Text=QuestionText.Text=TechniqueText.Text=FindingsText.Text=ImpressionText.Text=OriginalText.Text="";}
async void Search_Click(object sender,RoutedEventArgs e)=>await SearchAsync(1);async void Prev_Click(object sender,RoutedEventArgs e)=>await SearchAsync(Math.Max(1,page-1));async void Next_Click(object sender,RoutedEventArgs e)=>await SearchAsync(Math.Min(totalPages,page+1));async void SearchBox_KeyDown(object sender,KeyEventArgs e){if(e.Key==Key.Enter){e.Handled=true;await SearchAsync(1);}}
async void Reset_Click(object sender,RoutedEventArgs e){SearchBox.Text="";ModeBox.SelectedIndex=0;FieldBox.SelectedIndex=0;CtCheck.IsChecked=MrCheck.IsChecked=true;StudyBox.SelectedIndex=0;StatusBox.SelectedIndex=0;ImpressionBox.SelectedIndex=0;SortBox.SelectedIndex=0;PageSizeBox.SelectedIndex=1;await SearchAsync(1);}
void CopyImpression_Click(object sender,RoutedEventArgs e){if(current is not null&&!string.IsNullOrEmpty(current.Impression))Clipboard.SetText(current.Impression);}void CopyReport_Click(object sender,RoutedEventArgs e){if(current is null)return;Clipboard.SetText($"Klinische Angaben:\n{current.ClinicalInformation}\n\nFragestellung:\n{current.Question}\n\nMethodik:\n{current.Technique}\n\nBefund:\n{current.Findings}\n\nBeurteilung:\n{current.Impression}");}
async void Export_Click(object sender,RoutedEventArgs e){if(repo is null)return;var d=new SaveFileDialog{Title="Treffer als CSV exportieren",Filter="CSV-Datei (*.csv)|*.csv",FileName=$"BefundExplorer_Export_{DateTime.Now:yyyyMMdd_HHmm}.csv"};if(d.ShowDialog(this)!=true)return;try{StatusText.Text="Exportiere …";var sb=new StringBuilder();sb.AppendLine("ID;Modalität;Studienbeschreibung;Titel;Klinische Angaben;Fragestellung;Befund;Beurteilung;Strukturstatus");int p=1;while(true){var r=Request(p) with{PageSize=500};var res=await repo.SearchAsync(r);foreach(var x in res.Items)sb.AppendLine(string.Join(';',new[]{x.Id.ToString(),x.Modality,x.StudyDescription,x.Title,x.ClinicalInformation,x.Question,x.Findings,x.Impression,x.StructureStatus}.Select(Csv)));if(p>=res.TotalPages)break;p++;}await File.WriteAllTextAsync(d.FileName,sb.ToString(),new UTF8Encoding(true));StatusText.Text=$"Exportiert: {d.FileName}";}catch(Exception ex){MessageBox.Show(this,ex.Message,"Exportfehler",MessageBoxButton.OK,MessageBoxImage.Warning);}}
static string Csv(string? v)=>"\""+(v??"").Replace("\"","\"\"").Replace("\r"," ").Replace("\n"," ")+"\"";
void Theme_Click(object sender,RoutedEventArgs e){dark=!dark;Set("BackgroundBrush",dark?"#0F141A":"#F4F6F8");Set("SurfaceBrush",dark?"#171D24":"#FFFFFF");Set("SurfaceAltBrush",dark?"#1D252E":"#F8FAFC");Set("TextBrush",dark?"#E8EDF2":"#18202A");Set("MutedBrush",dark?"#98A4B3":"#667085");Set("BorderBrush",dark?"#303A45":"#D8DEE6");Set("AccentSoftBrush",dark?"#3B2025":"#F7E8EA");Set("SelectionBrush",dark?"#352228":"#FBEFF0");ThemeButton.Content=dark?"Hell":"Dunkel";}static void Set(string k,string c)=>Application.Current.Resources[k]=new SolidColorBrush((Color)ColorConverter.ConvertFromString(c));}
